- UC7_gcs09iThXybpVgjHZ_7g  # PBS Space Time
- UCYNbYGl89UUowy8oXkipC-Q  # Dr. Becky
- UCciQ8wFcVoIIMi-lfu8-cjQ  # Anton Petrov
- UCIBaDdAbGlFDeS33shmlD0A  # European Space Agency, ESA
- UCxzC4EngIsMrPmbm6Nxvb-A  # Scott Manley
